[demarc:syslog]
SHOULD_LINEMERGE = false
TIME_PREFIX = ^
TIME_FORMAT = YYYY-MM-DD HH:mm:ss
DATETIME_CONFIG = AUTO
MAX_TIMESTAMP_LOOKAHEAD = 15
LINE_BREAKER = (\r?\n)
TRUNCATE = 10000
TRANSFORMS-set_host = demarc-host-transform
